/* radical data — Casey Chinese School character explorer.
   Hand-curated: the 24 radicals that do the most work in the 300-character
   library on this page. Example characters are NOT listed here — they are
   matched live from CHAR_DATA by radicals.js (d.radical === r or v, or the
   character IS the full form), so they stay in sync with the library.
   Fields: r glyph · v full/variant form · py reading (empty when the radical
   has no everyday reading of its own) · en meaning · nick 中文 nickname +
   nickPy + nickEn · pos where it usually sits (bilingual) · mean what it
   signals · zhMean idiomatic 中文 one-liner · story where the shape comes
   from · tip optional watch-out · xtr extra examples beyond the 300.       */
window.RADICAL_DATA = [
{r:"氵",v:"水",py:"shuǐ",en:"water",nick:"三点水",nickPy:"sān diǎn shuǐ",nickEn:"three drops of water",
 pos:"on the left · 在左边",
 mean:"Anything wet: rivers 河, seas 海, washing 洗, swimming 游 — if it flows or splashes, look for the three drops.",
 zhMean:"带三点水的字，多和水有关：河、海、洗、游。",
 story:"It's 水 squeezed thin until only three little drops are left."},
{r:"亻",v:"人",py:"rén",en:"person",nick:"单人旁",nickPy:"dān rén páng",nickEn:"the standing person",
 pos:"on the left · 在左边",
 mean:"People and the things people do: 你 you, 他 him, 住 to live, 做 to do, 体 the body.",
 zhMean:"单人旁的字，多和人有关：你、他、住、做。",
 story:"人 standing up tall and pulling in thin, to make room for the rest of the character."},
{r:"口",py:"kǒu",en:"mouth",nick:"口字旁",nickPy:"kǒu zì páng",nickEn:"the mouth side",
 pos:"on the left — or anywhere a mouth fits · 在左边，或哪儿都行",
 mean:"Talking, eating and shouting: 吃 eat, 喝 drink, 叫 call, 唱 sing — and the little question words 吗, 呢, 吧 all chatter through a mouth.",
 zhMean:"口字旁的字，多和嘴巴有关：吃、喝、唱、叫。",
 story:"An open mouth, drawn square so it's easy to write. Two of them cry together in 哭.",
 tip:"Don't mix it up with the big box 囗 — that one wraps around a whole character, like 国 and 园."},
{r:"扌",v:"手",py:"shǒu",en:"hand",nick:"提手旁",nickPy:"tí shǒu páng",nickEn:"the lifted hand",
 pos:"on the left · 在左边",
 mean:"Hands at work: 打 to hit, 找 to look for, 把 to hold.",
 zhMean:"提手旁的字，多是手上的动作：打、找、把。",
 story:"手 with its five fingers folded down into three quick strokes."},
{r:"忄",v:"心",py:"xīn",en:"heart",nick:"竖心旁",nickPy:"shù xīn páng",nickEn:"the standing heart",
 pos:"on the left — or as 心 lying flat underneath · 在左边，或躺在下面",
 mean:"Feelings of every kind: 快 happy and quick, 怕 afraid, 慢 slow and calm. Flat 心 carries 想 (to think) and 怎 (how).",
 zhMean:"竖心旁的字，说的是心情：快、慢、怕。心字底也一样：想、怎。",
 story:"A heart stood upright on its tip so it can squeeze in beside the word."},
{r:"艹",py:"cǎo",en:"grass, plants",nick:"草字头",nickPy:"cǎo zì tóu",nickEn:"the grass hat",
 pos:"a hat on top · 戴在头上",
 mean:"Green growing things: 花 flowers, 草 grass, 菜 veggies — even 蓝 blue, named after a dye plant.",
 zhMean:"草字头的字，多和植物有关：花、草、菜。",
 story:"Two little sprouts pushing up through the soil in a row.",
 xtr:[["茶","chá","tea"],["药","yào","medicine"]]},
{r:"木",py:"mù",en:"tree, wood",nick:"木字旁",nickPy:"mù zì páng",nickEn:"the wood side",
 pos:"on the left — or holding up the bottom · 在左边或底下",
 mean:"Trees and wooden things: 树 tree, 校 school (once built of wood!), 本 the root of a book, 果 fruit on a branch.",
 zhMean:"木字旁的字，多和树木有关：树、果、本、校。",
 story:"A trunk with branches up top and roots reaching below."},
{r:"日",py:"rì",en:"sun, day",nick:"日字旁",nickPy:"rì zì páng",nickEn:"the sun side",
 pos:"on the left or on top · 在左边或上头",
 mean:"Sunshine and time: 早 morning, 晚 evening, 明 bright, 星 star — in Chinese, days are counted in suns.",
 zhMean:"日字旁的字，多和太阳、时间有关：早、晚、明、星。",
 story:"A round sun with a spot in the middle, squared off by the writing brush.",
 tip:"目 (eye) looks close — it has two lines inside, the sun has only one."},
{r:"月",v:"⺼",py:"yuè",en:"moon — and body parts",nick:"月字旁",nickPy:"yuè zì páng",nickEn:"the moon side",
 pos:"on the left or right · 在左边或右边",
 mean:"Moon and time words: 明 bright, 期 week, 朋 two moons side by side — friends. But here's its secret: on body words it is ancient 肉 (flesh) in disguise — 脑 brain, 服 clothes on the body, 能 (a bear's body!).",
 zhMean:"月字旁有两家：一家是月亮（明、期），另一家其实是「肉」，和身体有关（脑、服）。",
 story:"A crescent moon with two faint cloud lines drifting across it."},
{r:"讠",v:"言",py:"yán",en:"speech",nick:"言字旁",nickPy:"yán zì páng",nickEn:"the speech side",
 pos:"on the left · 在左边",
 mean:"Words doing work: 说 speak, 读 read, 请 please, 谢 thank, 课 lesson, 谁 who. If a character talks, 讠 is in it.",
 zhMean:"言字旁的字，多和说话有关：说、读、请、谢。",
 story:"Simplified from 言 — sound waves rising up from a mouth."},
{r:"辶",en:"walking, roads",nick:"走之底",nickPy:"zǒu zhī dǐ",nickEn:"the walking foot",
 pos:"wraps around the bottom-left · 从左下绕过来",
 mean:"Going somewhere: 过 to cross, 进 to enter, 远 far, 近 near, 道 the way. It carries its character off down the road.",
 zhMean:"走之底的字，多和走路、道路有关：过、进、远、近。",
 story:"A foot mid-stride, flattened into one long swoosh that the rest of the character rides on."},
{r:"宀",en:"roof, home",nick:"宝盖头",nickPy:"bǎo gài tóu",nickEn:"the treasure lid",
 pos:"a hat on top · 戴在头上",
 mean:"Home and indoors: 家 home, 字 a character raised under a roof, 完 finished and safely inside.",
 zhMean:"宝盖头的字，多和房子有关：家、字、完。",
 story:"A roof with a little chimney-dot on top.",
 xtr:[["安","ān","peaceful — safe at home"],["室","shì","a room"]]},
{r:"女",py:"nǚ",en:"woman",nick:"女字旁",nickPy:"nǚ zì páng",nickEn:"the woman side",
 pos:"on the left or underneath · 在左边或下面",
 mean:"Family words: 妈 mum, 她 she, 奶 milk and grandma — and 好, a mum with her child: good.",
 zhMean:"女字旁的字，多和女子、家人有关：妈、她、好、奶。",
 story:"An ancient drawing of a figure kneeling gracefully with folded arms."},
{r:"土",py:"tǔ",en:"earth, ground",nick:"提土旁",nickPy:"tí tǔ páng",nickEn:"the lifted earth",
 pos:"on the left or at the bottom · 在左边或底下",
 mean:"Ground and places: 地 the ground, 坐 two people sitting on the earth, 城 a city wall of packed earth, 在 to be somewhere.",
 zhMean:"提土旁的字，多和土地有关：地、坐、城、在。",
 story:"A little mound of clay sitting on the ground line.",
 tip:"士 (scholar) is the lookalike — on 士 the TOP stroke is the wide one."},
{r:"火",v:"灬",py:"huǒ",en:"fire",nick:"火字旁",nickPy:"huǒ zì páng",nickEn:"the fire side",
 pos:"on the left — or four sparks 灬 underneath · 在左边，或化作脚下四点",
 mean:"Heat and light: 热 hot, 点 to light a lamp. When fire slides under a character it melts into four little sparks: 灬.",
 zhMean:"火字旁的字，多和火、热有关：热、点。四点底「灬」也是火。",
 story:"A campfire with flames licking up on both sides."},
{r:"纟",py:"sī",en:"silk, thread",nick:"绞丝旁",nickPy:"jiǎo sī páng",nickEn:"the twisted silk",
 pos:"on the left · 在左边",
 mean:"Threads and cloth — and colours, because silk drank the dye: 红 red, 绿 green, 给 to hand over, 经 the threads of a loom.",
 zhMean:"绞丝旁的字，多和丝线、颜色有关：红、绿、给。",
 story:"A twisted skein of silk yarn, simplified to three quick strokes.",
 xtr:[["线","xiàn","thread"]]},
{r:"饣",v:"食",py:"shí",en:"food",nick:"食字旁",nickPy:"shí zì páng",nickEn:"the food side",
 pos:"on the left · 在左边",
 mean:"Everything tasty starts here: 饭 a meal. Spot the food side and your mouth can start watering.",
 zhMean:"食字旁的字，多和吃的有关：饭、饿、饺。",
 story:"Simplified from 食 — a lid over a steaming pot of rice.",
 xtr:[["饿","è","hungry"],["饺","jiǎo","dumpling"],["馆","guǎn","restaurant, hall"]]},
{r:"犭",v:"犬",py:"quǎn",en:"dog, animals",nick:"反犬旁",nickPy:"fǎn quǎn páng",nickEn:"the dog side",
 pos:"on the left · 在左边",
 mean:"Furry friends and wild ones: 狗 dog, 猫 cat — and a whole zoo beyond.",
 zhMean:"反犬旁的字，多是动物：狗、猫、猪、狼。",
 story:"A dog rearing up on its hind legs, drawn in three strokes.",
 xtr:[["猪","zhū","pig"],["狼","láng","wolf"],["狮","shī","lion"]]},
{r:"目",py:"mù",en:"eye",nick:"目字旁",nickPy:"mù zì páng",nickEn:"the eye side",
 pos:"on the left — or stacked in the character · 在左边或叠在里面",
 mean:"Looking and seeing: 看 a hand shading an eye, 眼 the eye itself, 睡 eyelids drooping off to sleep, 真 really — seen with your own eyes.",
 zhMean:"目字旁的字，多和眼睛有关：看、眼、睡。",
 story:"An eye stood up on its side; the two lines inside are the iris."},
{r:"雨",py:"yǔ",en:"rain, weather",nick:"雨字头",nickPy:"yǔ zì tóu",nickEn:"the rain hat",
 pos:"a hat on top · 戴在头上",
 mean:"Weather falling from the sky: 雪 snow — and beyond our 300, thunder 雷 and fog 雾.",
 zhMean:"雨字头的字，多和天气有关：雪、雷、雾。",
 story:"Raindrops falling from a cloud, under the long line of the sky.",
 xtr:[["雷","léi","thunder"],["雾","wù","fog"],["霜","shuāng","frost"]]},
{r:"门",py:"mén",en:"gate, door",nick:"门字框",nickPy:"mén zì kuàng",nickEn:"the gate frame",
 pos:"a frame around the character · 包在外面",
 mean:"Doorways and what happens in them: 问 a question poking its mouth 口 through the door.",
 zhMean:"门字框的字，多和门有关：问、闪、闹。",
 story:"Simplified from 門 — a pair of swinging saloon doors.",
 xtr:[["闪","shǎn","to flash, to dodge"],["闹","nào","noisy, lively"]]},
{r:"足",py:"zú",en:"foot",nick:"足字旁",nickPy:"zú zì páng",nickEn:"the foot side",
 pos:"on the left, squeezed into ⻊ · 在左边",
 mean:"Feet on the move: 跑 run, 跳 jump, 路 road, 跟 follow along behind.",
 zhMean:"足字旁的字，多和脚有关：跑、跳、路、跟。",
 story:"A kneecap drawn above a foot — it tucks in at the side as ⻊."},
{r:"刂",v:"刀",py:"dāo",en:"knife",nick:"立刀旁",nickPy:"lì dāo páng",nickEn:"the standing knife",
 pos:"on the right · 在右边",
 mean:"Cutting and splitting: 别 to separate, 到 to arrive — cutting straight to a place, 前 forward.",
 zhMean:"立刀旁的字，多和刀、切分有关：到、别、前。",
 story:"刀 turned on its side until only the blade's edge shows.",
 tip:"One of the few radicals that sits on the right-hand side."},
{r:"攵",en:"action, a tapping hand",nick:"反文旁",nickPy:"fǎn wén páng",nickEn:"the tapping hand",
 pos:"on the right · 在右边",
 mean:"A busy hand making things happen: 教 to teach, 放 to let go, 数 to count, 故 stories of long ago.",
 zhMean:"反文旁的字，多有「做事」的意思：教、放、数。",
 story:"A hand holding a little stick — tap, tap, tap.",
 tip:"It sits on the right and looks like 文 with an extra wiggle — its nickname means 'backwards 文'."},
];
